import getPosition from './positions';

const dev = [
  {
    id: 'dev-1',
    type: 'box',
    data: { label: 'Developer (Mid-level)', type: 'role' },
    position: getPosition(0, -0.5),
  },
  {
    id: 'dev-2',
    type: 'box',
    data: { label: 'Test-Driven Development', type: 'skill' },
    position: getPosition(-1.5, -1.5),
  },
  {
    id: 'dev-3',
    type: 'box',
    data: { label: 'Ava', type: 'skill' },
    position: getPosition(-2, -2.5),
  },
  {
    id: 'dev-4',
    type: 'box',
    data: { label: 'Mocha', type: 'skill' },
    position: getPosition(-1, -2.5),
  },
  {
    id: 'dev-5',
    type: 'box',
    data: { label: 'CircleCI', type: 'skill', info: true },
    position: getPosition(1, -1.5),
  },
  {
    id: 'dev-6',
    type: 'box',
    data: { label: 'Declarative', type: 'concept' },
    position: getPosition(3.5, -1.5),
  },
  {
    id: 'dev-7',
    type: 'box',
    data: { label: 'Functional', type: 'concept' },
    position: getPosition(3.5, -2.5),
  },
  {
    id: 'dev-8',
    type: 'box',
    data: { label: 'Subscriber Pattern', type: 'concept' },
    position: getPosition(3.5, -3.5),
  },
  {
    id: 'dev-9',
    type: 'box',
    data: { label: 'Bundling', type: 'concept', info: true },
    position: getPosition(2, -1.5),
  },
  {
    id: 'dev-10',
    type: 'box',
    data: { label: 'Babel', type: 'skill', info: true },
    position: getPosition(2, -2.5),
  },
  {
    id: 'dev-11',
    type: 'box',
    data: { label: 'Rollup', type: 'skill', info: true },
    position: getPosition(2, -4.5),
  },
  {
    id: 'dev-12',
    type: 'box',
    data: { label: 'Esbuild', type: 'skill', info: true },
    position: getPosition(3, -4.5),
  },
  {
    id: 'dev-13',
    type: 'box',
    data: { label: 'Webpack', type: 'skill', info: true },
    position: getPosition(4, -4.5),
  },
  {
    id: 'dev-14',
    type: 'box',
    data: { label: 'Module Types', type: 'concept', info: true },
    position: getPosition(2, -3.5),
  },
  {
    id: 'dev-15',
    type: 'box',
    data: { label: 'API Design', type: 'concept' },
    position: getPosition(-3, -1.5),
  },
  {
    id: 'dev-16',
    type: 'box',
    data: { label: 'Component-ization', type: 'concept', info: true },
    position: getPosition(-4.5, -1.5),
  },
  {
    id: 'dev-17',
    type: 'box',
    data: { label: 'Documentation', type: 'skill' },
    position: getPosition(-3, -2.5),
  },
  {
    id: 'dev-18',
    type: 'box',
    data: { label: 'Doc-Driven Development', type: 'skill' },
    position: getPosition(-3, -3.5),
  },
  {
    id: 'dev-19',
    type: 'box',
    data: { label: 'React Hooks', type: 'skill', info: true },
    position: getPosition(0, -1.5),
  },
  {
    id: 'dev-20',
    type: 'box',
    data: { label: 'React Context', type: 'skill', info: true },
    position: getPosition(0, -2.5),
  },
  {
    id: 'dev-21',
    type: 'box',
    data: { label: 'SPA Routing', type: 'concept', info: true },
    position: getPosition(0, -3.5),
  },
  {
    id: 'dev-22',
    type: 'box',
    data: { label: 'Docker', type: 'skill', info: true },
    position: getPosition(1, -2.5),
  },
  {
    id: 'dev-23',
    type: 'box',
    data: { label: 'Metadata', type: 'skill' },
    position: getPosition(-4.5, -2.5),
  },
  {
    id: 'dev-24',
    type: 'box',
    data: { label: 'MQL', type: 'skill' },
    position: getPosition(-4.5, -3.5),
  },
  {
    id: 'dev-25',
    type: 'box',
    data: { label: 'Render engine', type: 'skill' },
    position: getPosition(-4.5, -4.5),
  },
  { id: 'dev-e2-3', source: 'dev-2', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-3' },
  { id: 'dev-e2-4', source: 'dev-2', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-4' },
  { id: 'dev-e6-7', source: 'dev-6', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-7' },
  { id: 'dev-e7-8', source: 'dev-7', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-8' },
  { id: 'dev-e9-10', source: 'dev-9', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-10' },
  { id: 'dev-e10-14', source: 'dev-10', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-14' },
  { id: 'dev-e14-11', source: 'dev-14', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-11' },
  { id: 'dev-e14-12', source: 'dev-14', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-12' },
  { id: 'dev-e14-13', source: 'dev-14', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-13' },
  { id: 'dev-e15-16', source: 'dev-15', targetHandle: 'right', sourceHandle: 'left', target: 'dev-16' },
  { id: 'dev-e15-17', source: 'dev-15', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-17' },
  { id: 'dev-e17-18', source: 'dev-17', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-18' },
  { id: 'dev-e23-24', source: 'dev-23', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-24' },
  { id: 'dev-e24-25', source: 'dev-24', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-25' },
  { id: 'dev-e19-20', source: 'dev-19', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-20' },
  { id: 'dev-e20-21', source: 'dev-20', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-21' },
  { id: 'dev-e5-22', source: 'dev-5', targetHandle: 'bottom', sourceHandle: 'top', target: 'dev-22' },
];

export default dev;
